# Generated by Django 3.1.7 on 2021-04-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0002_admin_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='level',
        ),
        migrations.RemoveField(
            model_name='students',
            name='term',
        ),
        migrations.AddField(
            model_name='students',
            name='level_term',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='admin',
            name='confirm_password',
            field=models.CharField(default='', editable=False, max_length=5),
        ),
    ]
