# Generated by Django 3.1.7 on 2021-05-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0002_auto_20210511_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='admin',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
