# Generated by Django 3.1.7 on 2021-05-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0004_remove_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='picture',
        ),
    ]
