# Generated by Django 3.1.7 on 2021-05-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0005_remove_student_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='level_term',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
    ]
