# Generated by Django 3.1.7 on 2021-05-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0007_auto_20210526_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
    ]
