# Generated by Django 3.1.7 on 2021-05-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0010_auto_20210526_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.FileField(upload_to=''),
        ),
    ]
