# Generated by Django 3.1.7 on 2021-05-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0011_auto_20210526_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='picture',
        ),
    ]
